# Site settings
title: eQ Prototypes
email: hello@hamishtaplin.com
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onsdigital.github.io/eq-prototypes" # the base hostname & protocol for your site
twitter_username: onsdigital
github_username:  onsdigital

# Build settings
markdown: kramdown
